name: CI

on:
  [push, pull_request]


jobs:
  ci:
    strategy:
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit"]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - uses: leafo/gh-actions-luarocks@v4

      - name: install lua rocks
        run: |
          luarocks install busted
          luarocks install luassert

      - name: run test
        run: busted spec/
